### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stevedevney** [JEFworks/art-with-code#2]
Jean, what license are you doing this under?

Thanks, awesome work! I love it!

**Comment by JEFworks** [comment]
Thanks Steve! Good point! Addressed in commit 938e49f

**Comment by stevedevney** [comment]
Jean, the reason I asked about the license is my wife and I make some engravings that we sell on Etsy, and amazon. I was wondering if we could alter the code so it would engrave properly and possibly sell them if they looked neat. If we could I would make you the first one that turns out well. 

Thank you,

Steve Devney
651-800-8051

**Comment by JEFworks** [comment]
Hi Steve, Of course. Feel free to use the code for commercial purposes. I assume the licensing for the pictures you apply the code to (whether they allow for derivative works) will be the more pertinent licensing question. I would love one :) Thanks Steve!
